package crypto

import (
	"crypto/ed25519"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
)

// MasterPublicKeyHex is the production public key generated by the developer.
// Only signatures generated by the matching developer private key will pass verification.
const MasterPublicKeyHex = "89d0b76c099a10e0058d52fdb34902f94ccf2db1533c980c141253a18d8c3008"

type Verifier struct {
	publicKey ed25519.PublicKey
}

// NewVerifier creates a verifier configured with the hardcoded master public key.
func NewVerifier() (*Verifier, error) {
	return NewVerifierWithKey(MasterPublicKeyHex)
}

// NewVerifierWithKey creates a verifier with a specific public key (useful for tests).
func NewVerifierWithKey(pubKeyHex string) (*Verifier, error) {
	pubBytes, err := hex.DecodeString(strings.TrimSpace(pubKeyHex))
	if err != nil {
		return nil, fmt.Errorf("failed to decode master public key: %w", err)
	}
	if len(pubBytes) != ed25519.PublicKeySize {
		return nil, errors.New("invalid master public key length")
	}
	return &Verifier{publicKey: pubBytes}, nil
}

// BuildCanonicalMessage constructs a normalized deterministic payload byte slice:
// Format: command_type|target_hwid|sql_content
// This eliminates JSON key ordering and whitespace discrepancies between PowerShell/Supabase/Go.
func BuildCanonicalMessage(commandType, targetHWID, sqlContent string) []byte {
	cleanSQL := strings.TrimSpace(sqlContent)
	return []byte(fmt.Sprintf("%s|%s|%s", commandType, targetHWID, cleanSQL))
}

// VerifySignature verifies that the given hex-encoded Ed25519 signature
// matches the canonical message signed with the developer's private key.
func (v *Verifier) VerifySignature(commandType, targetHWID, sqlContent, signatureHex string) bool {
	sigBytes, err := hex.DecodeString(strings.TrimSpace(signatureHex))
	if err != nil || len(sigBytes) != ed25519.SignatureSize {
		return false
	}
	canonicalMsg := BuildCanonicalMessage(commandType, targetHWID, sqlContent)
	return ed25519.Verify(v.publicKey, canonicalMsg, sigBytes)
}
